# Generated by Django 3.1.2 on 2020-11-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='ID_user',
        ),
        migrations.AddField(
            model_name='post',
            name='Type_post',
            field=models.CharField(choices=[('P', 'Post'), ('Ev', 'Event'), ('BO', 'Buisness-offer')], default='P', max_length=3, verbose_name='Типы постов'),
        ),
        migrations.AddField(
            model_name='user',
            name='Type_user',
            field=models.CharField(choices=[('B', 'Business'), ('E', 'Expert'), ('C', 'Common')], default='C', max_length=3, verbose_name='Типы пользователей'),
        ),
        migrations.DeleteModel(
            name='PostType',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
