# Generated by Django 3.1.2 on 2020-11-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20201121_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Discription',
        ),
        migrations.AddField(
            model_name='post',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='Text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
    ]
